### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by MohamedEssamAdawy** [threefoldfoundation/wiki_example#1]
Return 404 - Not Found using publishing tools
![image](https://user-images.githubusercontent.com/11272864/105698787-0bad7f80-5f0f-11eb-9e35-2f3e3139f78b.png)

**Comment by abom** [comment]
Only README.md need to be added with any content.

**Comment by hossnys** [comment]
fixed here https://github.com/threefoldfoundation/wiki_example/commit/7b93d7f15a67dfa6c58eb19451df6306e186ad9e
